input-files:
- manuscript/zoteropicker.md
- manuscript/inlini.md
- manuscript/references.md

output-file: output.docx

bibliography: 
- src/citation.bib

filters:
- src/filters/inlini.py
- src/filters/apa_and.lua
- src/filters/makebib.py

citeproc: true

csl: src/apa7.csl