version: '3'
services:
  issakvsdoc:
    build:
      context: .
      dockerfile: Dockerfile
    image: issakuss/vsdoc:latest
    container_name: issakvsdoc
    volumes:
      - ../../:/mnt
      - ../../.ssh/:/home/issakuss/.ssh/
    stdin_open: true
    tty: true
    network_mode: "host"
    user: "22398:16003"
    entrypoint: []
    command: "/bin/bash --login"